Feat/017 frontend create admin dashboard
AlHassouna/Al-Manshaa-monorepo pull request #22
Opened 2023-03-29 12:29 UTC by EliasSalom

2023-03-29 13:13 UTC, HassanHassouna requested changes
Please handle the comments

2023-03-29 13:13 UTC, HassanHassouna commented on libs/system-design/src/lib/Table/Table.tsx
Please remove unnecessary code!

2023-03-29 18:53 UTC, EliasSalom commented on libs/system-design/src/lib/Table/Table.tsx
I update the comment we will use this code but not now, I already put a `TODO`

2023-03-30 09:49 UTC, EliasSalom commented
the comment has been resolved and the code updated, waiting for a new review!

2023-03-30 10:06 UTC, HassanHassouna approved these changes

2023-03-30 10:06 UTC, merged